apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebookapp
  labels:
    app: notebookapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebookapp
  template:
    metadata:
      labels:
        app: notebookapp
    spec:
      containers:
        - name: notebookapp
          image: 546518012212.dkr.ecr.us-east-1.amazonaws.com/app_repository:lattest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080